name: Build Zed

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0/24 * * 1-5'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone Zed
        uses: actions/checkout@v4
        with:
          repository: 'zed-industries/zed'

      - name: Setup Rust toolchain
        run: |
          rustup toolchain install stable |
          git config --system core.longpaths true |
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build Zed
        run: |
          cargo build --release -p zed

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zed-latest
          path: target/release/zed.exe
